---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-cilium.yml'
  ansible.builtin.import_playbook: playbook-cilium.yml

- name: 'Run playbook-gateway.yml'
  ansible.builtin.import_playbook: playbook-gateway.yml
